# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DeployBackend

on:
  push:
    branches: [ "Back" ]
    
jobs:
  TestAndDeploy:
    name: Test and Deploy to EC2 Backend
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the Backend branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd Back &&
          pip install -r requirements.txt
          
      # Set PYTHONPATH and run unit tests
      - name: Run Unit Tests
        env:
          PYTHONPATH: ${{ github.workspace }}/Back
        run: |
          cd Back &&
          pytest test/test_usuario.py --disable-warnings
          
      # Despliegue del Backend si las pruebas unitarias pasan
      - name: Deploy Back to EC2 Instance
        if: success()  # Solo ejecutar si las pruebas pasan
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST_BACK }}
          EC2_USER: ${{ secrets.USER_NAME }}
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              ls &&
              cd /home/ubuntu/Parcial1-BigData &&
              pwd &&
              git fetch --all &&
              git switch Back &&
              git reset --hard origin/Back &&
              git pull origin Back &&
              ls &&
              source /home/ubuntu/env/bin/activate &&
              pwd &&
              cd /home/ubuntu/Parcial1-BigData/Back &&
              pwd &&
              ls &&
              pip install -r requirements.txt &&
              fuser -k 5000/tcp || true &&
              tmux kill-session -t mysession || true &&  # Terminar sesiÃ³n existente si existe
              tmux new-session -d -s mysession "python Servidor.py> gunicorn.log 2>&1"
          '
